update from, dispatch, and pp

diff --git a/bin/pp b/bin/pp
--- a/bin/pp
+++ b/bin/pp
@@ -1,118 +1,165 @@
 #!/bin/sh -e
+#
+# https://www.romanzolotarev.com/bin/pp
+# Copyright 2018 Roman Zolotarev <hi@romanzolotarev.com>
+#
+# Permission to use, copy, modify, and/or distribute this software for any
+# purpose with or without fee is hereby granted, provided that the above
+# copyright notice and this permission notice appear in all copies.
+#
+# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
+# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
+# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
+# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
+# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
+# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
+# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
+#
 
 main() {
+	MAIL_TO='hi@romanzolotarev.com'
+	MAIL_SUBJECT='romanzolotarev.com: pp'
 	MAIL_QUEUE='/db/www/mail_queue'
 	CUSTOMERS='/db/www/customers'
-	NOW=$(date +%s)
 	PAGES='/htdocs/ppp'
-	mkdir -p "$CUSTOMERS"
-	test -d "$PAGES" || http500 "$PAGES no such directory"
-
-	case "$REQUEST_METHOD" in
-		POST) post;;
-		GET) get;;
-		*) http500 'invalid';;
-	esac
+	test "$REQUEST_METHOD" = "GET" && get
+	test "$REQUEST_METHOD" = "POST" && post
+	http500 'invalid method'
 }
+
+
+get() {
+	url="${PAGES}${REQUEST_URI%%\?*}"
+	if test "${url%%/}" = "$url"
+	then file="$url"
+	else file="${url}index.html"
+	fi
+
+	test -f "$file" || http404 "$file"
+
+	c="${HTTP_COOKIE##*customer=}"
+	test "$HTTP_COOKIE" = "$c" && register_form
+	c="${c%%;*}"
+	test -d "$CUSTOMERS/$c" || register_form
+
+	ap="${HTTP_COOKIE##*await_pin=}"
+	test "$HTTP_COOKIE" != "$ap" &&
+	test "${ap%%;*}" = 'true' &&
+	test -f "$CUSTOMERS/$c/pin" && log_in_form
+
+	s_key="${HTTP_COOKIE##*session_key=}"
+	test "$HTTP_COOKIE" = "$s_key" && register_form
+	s_key="${s_key%%;*}"
+	test -f "$CUSTOMERS/$c/sessions/$s_key" || register_form
+
+	test -f "$CUSTOMERS/$c/expires_at" || subscribe_form
+
+	echo 'Status: 200 OK
+Content-Type: text/html; charset=utf-8
+
+'
+	render_log_out_form
+	cat "$file"
+	exit 0
+}
+
 
 post() {
 	query=$(read_query_string_post) || http500 'invalid post'
-	action=$(get_value 'action' "$query")
-	case "$action" in
-		request_pin)
-			email=$(get_value 'email' "$query")
-			test -n "$email" || http401 'email is required'
-			request_pin "$email"
-			;;
+	a="${query##*action=}"
+	test "$query" = "$a" && http500 'no action'
+
+	case "${a%%&*}" in
 		register)
-			email=$(get_value 'email' "$query")
-			pin=$(get_value 'pin' "$query")
-			test -n "$email" || http401 'email is required'
-			test -n "$pin" || http401 'pin is required'
-			register "$email" "$pin"
+			e="${query##*email=}"
+			test "$query" = "$e" ||
+			test -z "$e" && http401 'email is required'
+			e=$(get_value "$query" 'email')
+			register "$e"
+			;;
+		log_in)
+			p="${query##*pin=}"
+			test "$query" = "$p" ||
+			test -z "$p" && http401 'pin is required'
+			p=${p%%&*}
+
+			e="${query##*email=}"
+			test "$query" = "$e" ||
+			test -z "$e" && http401 'email is required'
+			e=$(get_value "$query" 'email')
+			log_in "$e" "$p"
 			;;
 		subscribe)
-			c=$(get_cookie 'customer')
-			plan=$(get_value 'plan' "$query")
-			case "$plan" in
-			min) subscribe "$c" 60;;
-			month) subscribe "$c" "$((60 * 60 * 24 * 31))";;
-			year) subscribe "$c" "$((60 * 60 * 24 * 366))";;
-			*) http500 'invalid plan';;
+			p="${query##*plan=}"
+			test "$query" = "$p" ||
+			test -z "$p" && http401 'invalid plan'
+			p=${p%%&*}
+			case "$p" in
+				min) subscribe 60;;
+				month) subscribe 2678400;;
+				year) subscribe 31622400;;
+				*) http500 'invalid plan';;
 			esac
 			;;
-		logout) logout ;;
-		resend_pin) reset_cookies ;;
-		*) http500 'invalid request';;
+		log_out) log_out ;;
+		register_again) register_again ;;
+		kill_sessions) kill_sessions ;;
+		*) http500 'invalid action';;
 	esac
 }
 
+
 read_query_string_post() {
-	test -n "$CONTENT_LENGTH" || http500 'invalid content length'
+	test -n "$CONTENT_LENGTH" || http500 'invalid content'
 	dd bs=1 count="$CONTENT_LENGTH" status=none
 }
 
-get() {
-	file=$(get_filename)
-	test -f "$file" || http404 "$file"
-
-	c=$(get_cookie 'customer')
-	test -d "$CUSTOMERS/$c" || request_pin_form
-
-	ap=$(get_cookie 'await_pin')
-	test "$ap" = 'true' &&
-	test -f "$CUSTOMERS/$c/pin" && register_form
-
-	s_key=$(get_cookie 'session_key')
-	test -f "$CUSTOMERS/$c/sessions/$s_key" || request_pin_form
-
-	exp=$(get_last_sub_exp "$c")
-	test -n "$exp" || subscribe_form
-	test "$exp" -gt "$NOW" || subscribe_form
-
-	http200 "$(
-		echo "<pre>$c"
-		echo "$exp $(expires_in "$exp")"
-		echo "$s_key"
-		(cd "$CUSTOMERS/$c/sessions" && find . -type f -exec echo {} \; -exec cat {} \;)
-		echo "</pre>"
-		echo '<form action='"$REQUEST_URI"' method=post>
-<input name="action" type="submit" value="logout">
-</form>'
-		cat "$file"
-	)"
-}
 
 render_email_with_pin() {
 	email="$1"
 	url="$2"
-	meta="$SERVER_NAME $REMOTE_ADDR $(date '+%d/%b/%Y:%H:%M:%S %z')"
 
-	echo "To: $email"
-	echo 'MIME-Version: 1.0'
-	echo 'Content-Type: text/plain; charset=utf-8'
-	echo 'Content-Transfer-Encoding: 7bit'
-	echo 'Subject: PIN'
-	echo
-	echo "$url"
-	echo
-	echo ---
-	echo
-	echo "$meta"
+	echo 'To: '"$email"'
+MIME-Version: 1.0
+Content-Type: text/plain; charset=utf-8
+Content-Transfer-Encoding: 7bit
+Subject: '"${SERVER_NAME##www.}"': Complete your registration
+
+Here is your PIN: '"$pin"'
+
+Open this link to continue:
+
+'"$url"'
+
+---
+
+If you did not want to register just ignore this.
+Sent to: '"$email"'
+'
+}
+
+
+render_email_notification() {
+	body="$1"
+
+	echo 'To: '"$MAIL_TO"'
+MIME-Version: 1.0
+Content-Type: text/plain; charset=utf-8
+Content-Transfer-Encoding: 7bit
+Subject: '"${SERVER_NAME##www.}"': New customer
+
+'"$body"
 }
 
 
 get_value() {
-	echo "$2" |
-	tr '&' '\n' |
-	awk -F= '/^'"$1"'/{print$2}' |
-	decode_url
-}
-
-decode_url() {
 	# h/t Devin Teske
+	test -n "$1" || { echo; return; }
+	x="${1##*$2=}"
+	test "$x" = "$1" && { echo; return; }
+
 	# shellcheck disable=1004
-	awk '
+	echo "${x%%&*}" | awk '
 	BEGIN { for (n = 0; n < 256; n++) chr[n] = sprintf("%c",n) } {
 		t = $0
 		a = ""
@@ -127,41 +174,140 @@ decode_url() {
 	}'
 }
 
-register_form() {
-	p=$(get_value 'pin' "$QUERY_STRING")
-	http200 '<form action='"$REQUEST_URI"' method=post>
+
+encode_value() {
+	test -n "$1" || { echo; return; }
+	echo "$1" | awk '
+	BEGIN {
+		output = ""
+		for (n = 0; n < 256; n++) pack[sprintf("%c", n)] = sprintf("%%%02x", n) } {
+		sline = ""
+		slen = length($0)
+		for (n = 1; n <= slen; n++) {
+			char = substr($0, n, 1)
+			if ( char !~ /^[[:alnum:]_]$/ ) char = pack[char]
+			sline = sline char
+		}
+		output = output ( output ? "%0a" : "" ) sline
+	}
+	END { print output }'
+}
+
+
+log_in_form() {
+	e=$(get_value "$QUERY_STRING" 'email')
+	p=$(get_value "$QUERY_STRING" 'pin')
+
+	echo 'Status: 200 OK
+Content-Type: text/html; charset=utf-8
+
+<form action='"$REQUEST_URI"' method=post>
 <label>email</label>
 <input type="email" autocorrect="off" specllcheck="false" required="required"
-minlength="2" maxlength="255" autofocus="autofocus" name="email">
+minlength="2" maxlength="255" autofocus="autofocus" name="email" value="'"$e"'">
 <label>pin</label>
 <input type="text" autocorrect="off" specllcheck="false" required="required"
 minlength="4" maxlength="4" name="pin" value="'"$p"'">
-<input name="action" type="submit" value="register">
-<input name="action" type="submit" value="resend_pin">
+<input name="action" type="submit" value="log_in">
+</form><form action='"$REQUEST_URI"' method=post>
+<input name="action" type="hidden" value="register_again">
+<input type="submit" value="&lt; start over">
 </form>'
+	exit 0
 }
 
+
 subscribe_form() {
-	http200 '<form action='"$REQUEST_URI"' method=post>
-<label>select plan:</label><br>
+
+	echo 'Status: 200 OK
+Content-Type: text/html; charset=utf-8
+
+<form action='"$REQUEST_URI"' method=post>
+<label>select your plan:</label><br>
 <input type="radio" name="plan" value="min"><label>min</label><br>
 <input type="radio" name="plan" checked="checked" value="month"><label>month</label><br>
 <input type="radio" name="plan" value="year"><label>year</label><br>
 <input name="action" type="submit" value="subscribe">
-<input name="action" type="submit" value="logout">
 </form>'
+	render_log_out_form
+	exit 0
+
 }
 
-request_pin_form() {
-	http200 '<form action='"$REQUEST_URI"' method=post>
+
+kill_sessions() {
+	c="${HTTP_COOKIE##*customer=}"
+	test -z "$c" ||
+	test "$HTTP_COOKIE" = "$c" && http401 'no subscriber'
+	c="${c%%;*}"
+	test -d "$CUSTOMERS/$c" || http401 'no subscriber'
+
+	s_key="${HTTP_COOKIE##*session_key=}"
+	test -z "$s_key" ||
+	test "$HTTP_COOKIE" = "$s_key" && http401 'no session'
+	s_key="${s_key%%;*}"
+	test -f "$CUSTOMERS/$c/sessions/$s_key" || http401 'no session'
+
+	find "$CUSTOMERS/$c/sessions" -type f ! -name "$s_key" -delete
+
+	echo 'Status: 301 Moved Permanently'
+	echo "Location: $REQUEST_URI"
+	echo
+	exit 0
+}
+
+render_log_out_form() {
+	c="${HTTP_COOKIE##*customer=}"
+	test -z "$c" ||
+	test "$HTTP_COOKIE" = "$c" && http401 'no subscriber'
+	c="${c%%;*}"
+	test -d "$CUSTOMERS/$c" || http401 'no subscriber'
+
+	s_key="${HTTP_COOKIE##*session_key=}"
+	test -z "$s_key" ||
+	test "$HTTP_COOKIE" = "$s_key" && http401 'no session'
+	s_key="${s_key%%;*}"
+	test -f "$CUSTOMERS/$c/sessions/$s_key" || http401 'no session'
+
+	cd "$CUSTOMERS/$c/sessions"
+	sessions=$(find . -type f ! -name "$s_key"|wc -l|tr -d ' ')
+	echo '<form action='"$REQUEST_URI"' method=post>
+<input name="action" type="submit" value="log_out"></form>'
+
+	if test "$sessions" -ge "1"
+	then
+		echo '<form action='"$REQUEST_URI"' method=post>'
+		echo '<input name="action" type="hidden" value="kill_sessions">'
+		test "$sessions" = 1 && echo 'there is one more active session'
+		test "$sessions" -gt 1 && echo "there are $sessions other active sessions"
+		echo '<br><input type="submit" value="terminate all other sessions">'
+		echo '</form>'
+	fi
+
+	echo "<p>customer: $c<br>"
+	echo "session_key: $s_key</p>"
+}
+
+
+register_form() {
+	e="${QUERY_STRING##*email=}"
+	test "$QUERY_STRING" = "$e" && e=''
+	test -n "$e" && e=$(get_value "$QUERY_STRING" 'email')
+
+	echo 'Status: 200 OK
+Content-Type: text/html; charset=utf-8
+
+<form action='"$REQUEST_URI"' method=post>
 <label>email</label>
 <input type="email" autocorrect="off" specllcheck="false" required="required"
-minlength="2" maxlength="255" autofocus="autofocus" name="email">
-<input name="action" type="submit" value="request_pin">
+minlength="2" maxlength="255" autofocus="autofocus" name="email" value="'"$e"'">
+<input name="action" type="submit" value="register">
 </form>'
+	exit 0
 }
 
-reset_cookies() {
+
+register_again() {
 	echo 'Status: 301 Moved Permanently'
 	echo "Location: $REQUEST_URI"
 	echo 'Content-Type: text/html; charset=utf-8'
@@ -171,15 +317,25 @@ reset_cookies() {
 	exit 0
 }
 
-logout() {
-	c=$(get_cookie 'customer')
-	s_key=$(get_cookie 'session_key')
+
+log_out() {
+	c="${HTTP_COOKIE##*customer=}"
+	test -z "$c" ||
+	test "$HTTP_COOKIE" = "$c" && http401 'no subscriber'
+	c="${c%%;*}"
+	test -d "$CUSTOMERS/$c" || http401 'no subscriber'
+
+	s_key="${HTTP_COOKIE##*session_key=}"
+	test -z "$s_key" ||
+	test "$HTTP_COOKIE" = "$s_key" && http401 'no session'
+	s_key="${s_key%%;*}"
 	file="$CUSTOMERS/$c/sessions/$s_key"
-	test -f "$file" || http500 'no such session key'
-	rm "${file:?}"
+	test -f "$file" || http401 'no session'
+
+	rm "${file:?}" || http500 'cannot remove seesion'
 
 	echo 'Status: 301 Moved Permanently'
-	echo "Location: $REQUEST_URI"
+	echo "Location: ${REQUEST_URI%%\?*}"
 	echo 'Content-Type: text/html; charset=utf-8'
 	echo "Set-Cookie: customer=; HttpOnly"
 	echo "Set-Cookie: session_key=; HttpOnly"
@@ -188,20 +344,26 @@ logout() {
 	exit 0
 }
 
-request_pin() {
+
+register() {
 	email="$1"
 	pin=$(random_str 4)
 	c=$(sha256 -qs "$email")
 	dir="$CUSTOMERS/$c"
-	mkdir -p "$dir"
-	echo "$pin" > "$dir/pin"
-	url="${HTTP_REFERER%%\?*}?pin=$pin"
-	file="$MAIL_QUEUE/$(sha256 -qs "$c $pin")"
-	mkdir -p "$MAIL_QUEUE"
+	mkdir -p "$dir" && chmod 0770 "$dir"
+	file="$dir/pin"
+	echo "$pin $REMOTE_ADDR" > "$file"
+	chmod 0660 "$file"
+	url="${HTTP_REFERER%%\?*}?email=$(encode_value "$email")&pin=$pin"
+
+	mkdir -p "$MAIL_QUEUE" && chmod 0770 "$MAIL_QUEUE"
+
+	file="$MAIL_QUEUE/pp-$c"
 	render_email_with_pin "$email" "$url" > "$file"
+	chmod 0660 "$file"
 
 	echo 'Status: 301 Moved Permanently'
-	echo "Location: $REQUEST_URI"
+	echo "Location: ${REQUEST_URI%%\?*}?email=$(encode_value "$email")"
 	echo 'Content-Type: text/html; charset=utf-8'
 	echo "Set-Cookie: customer=$c; HttpOnly"
 	echo "Set-Cookie: await_pin=true; HttpOnly"
@@ -209,21 +371,29 @@ request_pin() {
 	exit 0
 }
 
-register() {
+
+log_in() {
 	email="$1"
 	pin="$2"
 	s_key=$(random_str 20)
 	c=$(sha256 -qs "$email")
 	p="$CUSTOMERS/$c/pin"
 	test -f "$p" || http401 'pin has not been requested'
-	test "$(cat "$p")" = "$pin" || http401 'invalid pin'
+	test "$(cat "$p")" = "$pin $REMOTE_ADDR" || http401 'invalid pin or remote_addr'
 	rm "$CUSTOMERS/$c/pin"
+
+	file="$CUSTOMERS/$c/email"
+	echo "$email" > "$file"
+	chmod 0660 "$file"
+
 	dir="$CUSTOMERS/$c/sessions"
-	mkdir -p "$dir"
-	echo "$NOW $REMOTE_ADDR $USER_AGENT" > "$dir/$s_key"
+	mkdir -p "$dir" && chmod 0770 "$dir"
+	file="$dir/$s_key"
+	echo "$REMOTE_ADDR" > "$file"
+	chmod 0660 "$file"
 
 	echo 'Status: 301 Moved Permanently'
-	echo "Location: $REQUEST_URI"
+	echo "Location: ${REQUEST_URI%%\?*}"
 	echo 'Content-Type: text/html; charset=utf-8'
 	echo "Set-Cookie: await_pin=false; HttpOnly"
 	echo "Set-Cookie: session_key=$s_key; HttpOnly"
@@ -232,56 +402,46 @@ register() {
 	exit 0
 }
 
-get_last_sub_exp() {
-	awk '/exp/{print$2}' "$(
-	find "$CUSTOMERS/$c/subs/" |
-	sort -n |
-	tail -n 1
-	)"
-}
-
-extend_exp() {
-	exp="$1"
-	duration="$2"
-	test -z "$exp" && echo $((NOW + duration)) && return
-	test "$NOW" -lt "$exp" && echo $((exp + duration)) && return
-	test "$NOW" -ge "$exp" && echo $((NOW + duration)) && return
-}
 
 subscribe() {
-	c="$1"
-	duration="$2"
-	exp=$(extend_exp "$(get_last_sub_exp "$c")" "$duration")
-	dir="$CUSTOMERS/$c/subs"
-	mkdir -p "$dir"
-	printf 'exp: %s\ntime: %s' "$exp" "$NOW" > "$dir/$NOW"
+	c="${HTTP_COOKIE##*customer=}"
+	test "$query" = "$c" ||
+	test -z "$c" && http401 'no customer'
+	c="${c%%;*}"
+
+	s_key="${HTTP_COOKIE##*session_key=}"
+	test "$HTTP_COOKIE" = "$s_key" ||
+	test -z "$s_key" && http401 'no session'
+	s_key="${s_key%%;*}"
+	test -f "$CUSTOMERS/$c/sessions/$s_key" || http401 'no session'
+
+	duration="$1"
+	now="$(date +%s)"
+
+	file="$CUSTOMERS/$c/expires_at"
+	echo "$((now + duration))" > "$file"
+	chmod 0660 "$file"
+
+	dir="$CUSTOMERS/$c/subscriptions"
+	mkdir -p "$dir" && chmod 0770 "$dir"
+	echo "duration: $duration" > "$dir/$now"
+
+	file="$MAIL_QUEUE/pp-n-$c"
+	render_email_notification "email: $email\ncustomer: $c\nduration: $duration" > "$file"
+	chmod 0660 "$file"
 
 	echo 'Status: 301 Moved Permanently'
-	echo "Location: $REQUEST_URI"
+	echo "Location: ${REQUEST_URI%%\?*}"
 	echo 'Content-Type: text/html; charset=utf-8'
 	echo
 	exit 0
 }
 
-get_filename() {
-	url="/htdocs/ppp${REQUEST_URI%%\?*}"
-	test "${url%%/}" = "$url" && echo "$url" && return
-	echo "${url}index.html"
-}
-
-get_cookie() {
-	echo "$HTTP_COOKIE" | tr ';' '\n' |
-	sed "/$1=/!d;s/ *$1=//g"
-}
-
-get_prop() {
-	tr ';' '\n' < "$2" |
-	sed "/$1=/!d;s/ *$1=//g"
-}
 
 random_str() {
 	jot -rcs '' "$1" 97 122
 }
+
 
 http500() {
 	echo 'Status: 500 Internal Server Error'
@@ -290,12 +450,6 @@ http500() {
 	exit 1
 }
 
-http404() {
-	echo 'Status: 404 Not Found'
-	echo
-	echo "404: $1"
-	exit 1
-}
 
 http401() {
 	echo 'Status: 401 Unauthorized'
@@ -304,54 +458,12 @@ http401() {
 	exit 1
 }
 
-http301() {
-	echo 'Status: 301 Moved Permanently'
-	echo "Location: $1"
+
+http404() {
+	echo 'Status: 404 Not Found'
 	echo
-	exit 0
-}
-
-http200() {
-	echo 'Status: 200 OK'
-	echo 'Content-Type: text/html; charset=utf-8'
-	echo
-	echo "$1"
-	exit 0
-}
-
-render_template() {
-	# h/t Devin Teske
-	awk '
-	BEGIN {
-		w = "[a-zA-Z_][a-zA-Z0-9_]*"
-		var = sprintf("\\$(%s|{%s})", w, w)
-	} {
-		str = ""
-		tail = $0
-		while (match(tail, var)) {
-			head = substr(tail, 1, RSTART - 1)
-			repl = substr(tail, RSTART, RLENGTH)
-			tail = substr(tail, RSTART + RLENGTH)
-			if ((match(head, /\\+/) ? RLENGTH + 1 : 1) % 2 == 1) {
-				sub(/^\$/, "", repl)
-				gsub(/(^{|}$)/, "", repl)
-				repl = ENVIRON[repl]
-			}
-			str = str head repl
-		}
-		str = str tail
-		print str
-	}'
-}
-
-expires_in() {
-	printf 'expires '
-	delta=$((exp - NOW))
-	test "$delta" -lt      2 && echo                      'now'  && return
-	test "$delta" -lt    120 && echo           "in $delta secs"  && return
-	test "$delta" -lt   7320 && echo "in $((delta/   60)) mins"  && return
-	test "$delta" -lt 172800 && echo "in $((delta/ 3660)) hours" && return
-	test "$delta" -ge 172800 && echo "in $((delta/86400)) days"  && return
+	echo "404: $1"
+	exit 1
 }
 
 
